version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  testlink:
    image: 'bitnami/testlink:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'apache_data:/bitnami/apache'
      - 'testlink_data:/bitnami/testlink'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  apache_data:
    driver: local
  testlink_data:
    driver: local